### ISSUE TITLE
Acheter un nom de doamine pour le site ?

### ISSUE THREAD

**Issue by SBats** [SBats/free-sign-language-website#6]
Il a été suggéré par Hocine d'acheter une nom de domain pour le site.
Je ne suis pas convaincu de l'utilité étant donné qu'il est accessible à cette adresse dors et déjà : http://signotheque.github.io/website/

Nous ne sommes pas suffisament structuré pour aller dépenser de l'argent sur un nom de domaine, et je ne suis personellement pas fan d'avoir le projet rattaché à une association via son nom (cf: le http://www.signotheque.arboresign.org/ qui était avant actif).

Vos avis ?

**Comment by ArboreSign** [comment]
Bonjour 
Oui pas de problème
Combien ca coute ?
Hocine

**Comment by Sungja** [comment]
Je suis d'accord avec toi. Inutile de sortir la quincaillerie, il n'y a pas encore d'indiens..

Et finalement, je me rends compte qu'on n'a pas besoin d'avoir une caserne.

**Comment by ghost** [comment]
Pour le moment Github fait très bien l'affaire. A voir quand le projet aura grossi et mûri.

**Comment by SBats** [comment]
Ok je clos pour l'instant et éventuellement on réouvre l'issue pour en rediscuter si besoin
